### ISSUE TITLE
Modal cuts off field to change username in certain situations

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1035]
![image1(3)](https://user-images.githubusercontent.com/8144640/127487527-fdd49fd3-004f-4eee-876e-5afbb9bc97bb.png)

> iOS Version: 14.6
> Device: iPad mini (5th generation)
> App Version: 3.3.1 (600)
> User ID: 863db61d-f543-43ef-a077-c45d0e6b5791
> Level: 10
> Class: rogue
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by saraolson** [comment]
this might be ipad only?

**Comment by juanj** [comment]
This happens on an iPad in landscape mode. At first, when the alert is just shown, the text field is visible. But as soon as the keyboard is shown, it disappears and never becomes visible again until the app is killed.
It also happens if you open the alert on an iPhone in landscape mode.

The problem is in the way `HabiticaAlertController` calculates its size.
It's calculating all the available space, but it fails to take into consideration that the available space may not be enough in some circumstances (iPhone/iPad landscape and/or keyboard shown). So, it can result in the content of the alert (in this case the text field) having a height of 0.

**Comment by saraolson** [comment]
we made some changes to modals in 3.4, need to check to see if this is fixed or worse lol
