### ISSUE TITLE
Chatbox uses a serif typeface

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1046]
:( please make it use sans serif SF (not comic sans)

**Comment by juanj** [comment]
This is an issue of the (now deprecated) library used for the chat: [SlackTextViewController](https://github.com/slackhq/SlackTextViewController).

The problem arises when trying to set a system font as the custom font. Because the textView used for the input do not set the font directly, but instead tries to create a new font instance with the same name and the calculated size, it ends up trying to create a font with a dot prefixed font name (e.g. ".SFUI-Regular").

https://github.com/slackhq/SlackTextViewController/blob/178750fe96fe3d67819df9ee660705907c427b55/Source/SLKTextView.m#L520

This results in the following message being printed in the console:
```
CoreText note: Client requested name ".SFUI-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].
```

From Apple:
> As mentioned in numerous WWDC sessions, dot-prefixed font names are not to be directly used.

Possible solutions:
1. Create a custom fork of the library and modify the code to address this issue
2. Set a concrete font as the custom font instead of using the system one
