### ISSUE TITLE
Remove FB authentication from Register and Settings screens

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1084]
New accounts won't have this option anymore and it won't be an option to add as an authentication method in Settings if people don't already use it. Anyone who use FB login already can still use it to access their account from the login screen as usual.

**Comment by rolisanchez** [comment]
While it is possible to just hide the FB authentication button while in the Register screen, the button is the same for Login and Register. This buttons calls an FBSDK method to get a token, then calls `userRepository.login` with this token.

Besides hiding the Facebook button from the Register screen, I believe the backend should search for the userId, and if this userId doesn't exist in the DB already it should reject new users from registering with a FB Access token. 

This way even if a user that likes to experiment is trying to "register" by clicking the Facebook button on the Login screen, the server should reject this and return a message like "Sorry but since December 2021 you can't create new accounts with Facebook :("

**Comment by saraolson** [comment]
@rolisanchez while that would be a more sure way to stop registration, we only hid the button as a quick way to stem the flow of new fb accounts. the end goal is to actually remove fb auth all together and when we get to that point we'll be much more thorough.

**Comment by saraolson** [comment]
already done this on android, time for ios

**Comment by rolisanchez** [comment]
Managed to get this by hiding the FB button on the register screen and applying the appropriate constraints for the Stack View:

https://user-images.githubusercontent.com/7276421/138528129-d3ee825d-b874-4c35-a7a9-fde65e3ccd09.mp4

**Comment by rolisanchez** [comment]
Created PR #1108 to hide FB button on register :)

**Comment by saraolson** [comment]
@rolisanchez our dev is actually the one working on this issue, and he's beta testing it now. Keep an eye out for the 'Help Wanted' label to be sure its not something we're planning to take on internally!
