### ISSUE TITLE
Crash when opening edit for Daily scheduled every X days when in Italian

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1097]
Very specific crash lol but happens every time. The key is switching language to Italian. When you tap a daily thats scheduled to repeat every X days (tried 3 days and 5 days) when app is in Italian, it crashes before it can load up the edit screen.

**Comment by rolisanchez** [comment]
I can confirm this happens in Spanish, Portuguese, German and Chinese too.

It seems the localization of the text "Repeats every %d %@" (For example, "Repeat every 3 days") is crashing the app. The problem seems to be in some localizations that are not using both variables passed, and this might cause some problem with memory.
 
See image below for the every_x localization, many are just using just %@. 

<img width="350" alt="Screen Shot 2021-10-19 at 17 58 22" src="https://user-images.githubusercontent.com/7276421/137989657-6b3ea686-c1ff-4a45-b285-d145df4c9f81.png">

I fixed the Spanish & Portuguese localization to use "cada %d %@" (Cada 3 dias) and the app stopped crashing. This also fixes German (jeden 3 Tage) and Chinese (每3日, though 天 may be more appropriate than 日? some native speaker?).

So I guess using both variables could fix the crash. I could fix the other languages too.

**Comment by rolisanchez** [comment]
Submitted PR #1102  to fix this :)
