### ISSUE TITLE
Opening Party or Guild chat causes app to crash

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitrpg-ios#1113]
**Describe the crash**
Two users have reported the issue as follows:

-  "I've been with the new App update for a few weeks and the problem I had previously hasn't been solved yet. That's me when I want to see the comments of my party I can't see them, because when I touch the tab to open it it closes and I have to open the App again if I can see the comments neither on my iPhone nor my iPad. My iOS is 15.1 and the version of Habitica is 3.4.2 (631)."
- "Every time that I try to access my Party page, the app closes and I have to reopen it. I have checked for updates and cleared my cache. I cannot access anything with my party at all."

**To Reproduce**
I am not able to reproduce this issue on my iPhone 11 Pro Max (OS 14.8, App Version 3.4.2 (631).

**Smartphone (please complete the following information):**
User One 
- Device: iPhone XS
 - OS: 15.1
 - App Version: 3.4.2 (631)
 - Habitica Username: hoyestoyfeliz
 
User Two
 - Device: iPhone 12 Pro Max
 - OS: 14.8
 - App Version: 3.4.2 (631)
 - Habitica Username: vengerbergvixen

**Comment by beffymaroo** [comment]
Additional user report from admin email:

Please describe the bug you encountered:

I was added to a party, I can accept quest invitations and I see the party chat notifications. I am participating in the quests/doing damage. Whenever I click “party” on the app, or click on a party chat notification, it crashes.

Would love to see if there’s a way to fix it, so that I can start quests with the party and participate in the chat.



The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.8.1
Device: iPhone 8
App Version: 3.4.6 (656)
User ID: d367d1d4-5ca8-49f6-be65-1262b97159a4
Level: 104
Class: mage
Is in Inn: false
Uses Costume: true
Custom Day Start: 5
