### ISSUE TITLE
Make messaging more clear when you're taking damage due to quest boss after party member checks in

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitrpg-ios#1136]
>iOS Version: 14.8.1
>Device: iPhone 8
>App Version: 3.4.3 (641)
>User ID: a6ba675e-ab8a-4025-8aeb-75bce0ff6669
>Level: 60
>Class: rogue
>Is in Inn: false
>Uses Costume: true
>Custom Day Start: 0
>"Occasionally when I hit the + on a habit or check off a daily, I will receive some amount of xp/coins/dmg to bosses as is normal, but also at the same time I will take a hit to my hp - that is, what should be “+1.45 hp” will appear as “-1.45”.
I had just leveled up earlier today (and so was at full health), when this bug happened again and I was able to confirm that it was indeed actually penalizing my hp (not just misreporting - I know that in the past when you leveled up it restored your health but the little pop-up notice displayed as “-48.50 hp“ or whathaveyou)."

**Comment by saraolson** [comment]
this isn't actually a bug, its because the user is on a quest. their party mate probably checked in, didn't do some dailies so the boss did damage. the server is just applying that at the same time as the user checks their habits. we could definitely try to improve this so the messaging is clearer about what's going on.

**Comment by saraolson** [comment]
This would need to be handled on the server side, so closing here. I've added an issue on the web repo to look at this
