### ISSUE TITLE
Make an Apple Watch app

### ISSUE THREAD

**Issue by ryhaph** [HabitRPG/habitrpg-ios#1248]
Requesting that we start developing this :) Would potentially massively increase habitica usage for iPhone users which is the majority of people in the US. As a productivity app, ease-of-use is paramount and having it strapped to the user's wrist greatly increases the chance that it will be used, increases its usefulness, and eliminates some friction which will in turn encourage a higher level of utilization for current users. For example, I could easily track my workouts and other things in Habitica but am forced to use other apps to do so if I want to use my apple watch; same with shopping lists, while shopping it's bothersome to have my phone glued to my hand. As a result of this inconvenience, I find myself tracking less things through habitica, simply for the fact that it forces me to use my phone. This may just be an enhancement, but it is a HUGELY IMPORTANT ONE! Please consider the priority carefully as making this feature could dramatically improve the popularity and trajectory of this project :) One thing to consider is user retention as every relevant competitor to Habitica has an Apple Watch app.

**Comment by saraolson** [comment]
Hi @ryhaph! Thanks for your interest in an Apple watch app for Habitica. While we would love to develop one, we have a backlog of other features and issues we're trying to get through first. We prefer to keep our GitHub for bugs and enhancements rather than large features, so I'm going to close this as it is very much already on our minds.
