### ISSUE TITLE
Incorrect calculation for tableView offset for in-call (or navigation) Status bar 

### ISSUE THREAD

**Issue by kyle-fox** [HabitRPG/habitrpg-ios#125]
This bug only occurs if the tab is instantiated while the in-call status bar is active. Currently, the content offset is being set as a hard coded value [here](https://github.com/HabitRPG/habitrpg-ios/blob/master/HabitRPG/HRPGTopHeaderNavigationController.m#L79). I'm not sure what the best fix for this would be at the moment, because the in-call status bar cannot be detected at launch. Converting to autolayout is probably the best bet and will be valuable in the future.

![in-call status bar](https://cloud.githubusercontent.com/assets/654722/8891295/b7855bf2-32f1-11e5-9ea2-952cb11a2413.png)

**Comment by vIiRuS** [comment]
According to http://stackoverflow.com/questions/1114557/resize-for-in-call-status-bar there should be a call to `viewWillLayoutSubviews`, when the status bar resizes. and then the height can be figured out with `[UIApplication sharedApplication].statusBarFrame.size.height`.

Not sure if autolayout helps here (the only part without autolayout is the top header), as the problem is with the content offset for the tableview. Which, afaik, isn't affected through autolayout. We can probably update the content offset in the `viewWillLayoutSubviews` of the tableviewcontroller. Although I haven't tested yet if  `viewWillLayoutSubviews` is called on the tableviewcontroller too when then statusbar resizes.
