### ISSUE TITLE
royal purple potion shouldn't show gryphon eggs as hatchable

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1254]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.7
> Device: iPhone SE (2nd generation)
> App Version: 3.6.1 (746)
> User ID: 04ca05cd-aaf1-4f2c-9e66-e329c7fa7eb5
> Level: 127
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Please describe the bug you encountered:
> When selecting royal purple potion -> use on egg, the griphon egg is not blurred out, indicating that I can use the potion on the griphon, but when I do so there is an error.
> 
> Expected behavior: the griphon is blurred just like all the other eggs which won’t hatch to this colored pet.
![image0](https://user-images.githubusercontent.com/102926641/197545457-845ca724-b79a-4000-b6ad-ccbe3e291cd1.png)

**Comment by saraolson** [comment]
royal purple gryphon is a special pet given out for events, which is why the error happens. so yeah, we should check to be sure the pet is actually hatchable w/ the potion combo. 

i think royal purple gryphons are the only case that would cause this specific confusion since they exist, but the potion is only usable on standard pets.
