### ISSUE TITLE
Allow the app to rotate

### ISSUE THREAD

**Issue by Shadallark** [HabitRPG/habitrpg-ios#141]
Good day to all of you;

Is there a reason that we are only allowing the app to be used in the Portrait orientation?

In some situations it might be beneficial to be able to have wider fields visible on the screen.

Shadallark

**Comment by vIiRuS** [comment]
At the time i made this setting something caused problems with landscape and biggest iphone was the 5(s), where landscape wouldn't have made much sense anyway. Unfortunately i can't remember what the problem was anymore, so it might not even exist anymore. Especially for iPad this would be important though.
In theory it's only adding the additional rotations in the app config and then checking that nothing broke. But that testing might be a bit work.
