### ISSUE TITLE
iOS 6 compatibility

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitrpg-ios#167]
Is this possible or at least not tricky to do? I've seen a couple of posts in the Tavern asking about this. I have an iPod 4th gen that unfortunately did not get the update to iOS 7, it would be awesome to be able to run the native app anyway.

**Comment by vIiRuS** [comment]
It may be possible, but it definitely is not feasible. The differences between iOS 7 and iOS 6 are pretty big (especially design wise), so that iOS 6 compatability would be a lot of work. As I also don't have an iOS 6 device or simulator I wouldn't be able to even test if the app works there. So this will, unfortunately, not be done.
