### ISSUE TITLE
[v 1.1 (68)] Ensure user data is loaded before displaying initial tableview

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#188]
Initially when opening the newest version of the app, it loaded a null screen. Reloading fixed the problem, and it has not recurred.

**Comment by lemoness** [comment]
Screenshot attached: 
![img_3490](https://cloud.githubusercontent.com/assets/3494081/9870201/c953bf20-5b3e-11e5-9cdb-dbf596a0237a.jpg)

**Comment by vIiRuS** [comment]
I tried to reproduce this and might have partially reproduced it.

When logged into the app, I deleted the app and reinstalled it. This keeps the keystore but deletes the database (so login data is still there, but user data is gone). After opening the newly installed app I reached the sate you pictured, but after a few seconds it updated with the new userdata. Is it possible that this is what happened to you but with a slower connection so that it appeared empty for several seconds and you refreshed?

**Comment by lemoness** [comment]
Yes, that's possible! And I agree that displaying something like the static page would be preferable.

**Comment by vIiRuS** [comment]
When the new launch screen is added, a check should be added that the user data is already present. if not, the launch screen should remain with a spinner until the data is available.

**Comment by lemoness** [comment]
(Just confirmed that this is indeed exactly what is happening! It eventually loaded even without a refresh.)
