### ISSUE TITLE
Tutorial Revamp 1 - Feedback

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#213]
Feel free to split off any of the things mentioned into their own tickets if necessary.

When I opened the phone, I immediately saw the new tutorial, even though I was logged into my old account. Preexisting users should not trigger the tutorial immediately. As a result, the avatar throughout was my current Habitica avatar.

![img_3612](https://cloud.githubusercontent.com/assets/3494081/10276204/d46fe0fe-6b02-11e5-8a9a-99cc2882fb93.PNG)

Seeing this written out, I think it's too long. I'm also wondering, is there a way to make the text scroll in like it does in games, to encourage people to read it? 

New text:
(Header) Welcome to Habitica!
(Main text) Want to improve your real-life Habits by treating life like a game?
(Button) I'm Ready!

![img_3613](https://cloud.githubusercontent.com/assets/3494081/10276210/df88c47e-6b02-11e5-9318-5cbf525da0a4.PNG)

- I think maybe Justin should scroll off and the avatar should appear, so that the focus is on your avatar.
- Not all skin colors are shown.

![img_3615](https://cloud.githubusercontent.com/assets/3494081/10276217/e83076c6-6b02-11e5-951d-afbc5973777f.PNG)

- Having just "choose a hairstyle" seems too plain by itself. Maybe it could keep the explanation text from the previous slide? We'll need to experiment with this.
- The bangs should also be available to select on this screen. 
- The bald hairstyle should be on the leftmost side.

![img_3616](https://cloud.githubusercontent.com/assets/3494081/10276198/cab86676-6b02-11e5-9a81-e82e8cd1dd91.PNG)

- Black hair is shown twice. I was unable to click on the one in the second row. 

![img_3617](https://cloud.githubusercontent.com/assets/3494081/10276247/1ecc4390-6b03-11e5-898c-7ddce6ecb165.PNG)

This slide was simply broken - everything was cut off! Also, perhaps because I already had a full account, selecting "Household" and clicking "Next" added no new tasks.

--

I wanted to test it again as an actual new user, so I logged out and registered for an account. The registration was successful, but immediately after the first tutorial screen popped up, it crashed the build. Since then, I have not been able to open the build without it crashing, even after shutting and restarting the app.

**Comment by lemoness** [comment]
Thinking about this more, is there any way to consolidate bangs, hairstyle, and hair color into one slide, or will it get too cramped?

**Comment by vIiRuS** [comment]
There are tei ways to only show the setup for new users.
1. save the state on the server and set it to "finished" for all existing users
2. only display it after the register flow
Which one would you prefer?

You mean that the text is "typed out"? I was planning on implementing that today.

As it's stil judtin talking to the user i wanted to still have him there. But i'll remove him so that there js more focus on the avatar.
You should be able to scroll to see all skin colors.

Or Maybe make the instructional prompt bigger? I'll test both and make screenshots
I'll add bangs and fix sorting

Not sure why black is there twice. I'll investigate

As mentioned when uploading the build: as we haven't decided yet if the pre made tasks should be saved in the app or served via the api, this last slide is very unfinished. (It's mostly just there to have the complete flow work with the other views)

**Comment by vIiRuS** [comment]
Combining hair style, color and bangs into one would cause the view to be pretty long and scroll on all devices. Right now it scrolls on older iphones (5s and lower) and doesn't scroll on iphones past the iphone 6.

**Comment by lemoness** [comment]
Ah, interesting. If it scrolls, we definitely need some visual indicator to
do that. However, could the skins just wrap around instead like the hair
does? I think that would look better.

As for the hair - that's fine, let's keep color and style separate, then.
Maybe hair color should be before hair style.

Looking forward to the typed text!

**Comment by lemoness** [comment]
As for preventing existing users from seeing the tutorial - what would be
the functional difference in user experience for each difference?

**Comment by vIiRuS** [comment]
It wraps exactly like the hair styles. Due to the description, everything is longer, which means it can't fit everything on the screen at once. (at least on smaller iPhones. iphone 6 (plus) displays everything on one screen).
Not sure what kind of scroll indicator would be best, as none of the other views have something like that.

**Comment by vIiRuS** [comment]
Thinking about it, saving the setup progress on the server wouldn't make much sense. then we would have to set it to "seen" for website signups too. I'll change it to only trigger on registrations.
