### ISSUE TITLE
Armoire drop chances are off

### ISSUE THREAD

**Issue by EdmundMagus** [HabitRPG/habitrpg-ios#238]
I've held off on reporting this issue, because I was trying to convince myself that I was just unlucky. However, this has been going on for a while now, and the outcomes I'm getting are looking vanishingly unlikely unless there's some sort of issue. The armoire is supposed to drop equipment 60% of the time. However, for me, the chances are definitely closer to 15-20%; mostly I get food and XP, and getting any equipment items is an unusual event. As you might imagine, this is a bit draining, especially since I don't particularly want XP - I don't really want to level up too quickly at this stage. This has been happening for a few months now; when it first started it was so noticeable that I assumed that the drop chances had been changed. My UID is 8be99c62-8b7d-47c6-9258-ba2e7e21f26b.

**Comment by lemoness** [comment]
Sorry about this frustration! So, the drop chances are indeed correct, but after some investigation, I have a hypothesis about what might be happening.

Since you posted this in the iOS repo, I'm assuming that you are primarily using the iOS app (definitely tell me if that's not the case). I've just realized that on the iOS app, there is no indicator when you have earned all of the equipment from the Armoire, which is an issue.

The Enchanted Armoire has a set amount of equipment in it, and more is added each month. (At the moment, there are about thirty pieces.) On the website, it displays how many pieces are left, and has a pop-up when you have them all. The new pieces are announced each month in the news; until they are added, users can continue to click the Armoire for a chance at food or XP. However, on the iOS app, there is no indication of how much equipment is left in the Armoire, and no announcement when you've earned all the current pieces.

I think that what happened is, a few months ago, when the chances of equipment drastically decreased, it was because you ran out of equipment. Since then, a few new pieces of equipment have been released, and you've obtained those, too, but in the meantime, all taps on the Armoire would only get you food and XP, making the chances of getting Equipment seem very low.

Does this seem like a plausible explanation for what's going on? If so, we'll change the title and purpose of this ticket to be having an equipment indicator for the Armoire.

**Comment by EdmundMagus** [comment]
Thanks for following up on thurs so promptly. Unfortunately, your
explanation doesn't really work - I must have posted this in the iOS repo
by mistake, for which I applogise, but I'm usually on the web app and
haven't ever even attempted to use the Armoire in iOS. I can see exactly
how much equipment is left, which is why it's frustrating that it's taking
me a really long time to get items. I'm sorry that I don't have the
figures, as I assumed at first it was just bad luck, but I can start
collecting data if that's helpful. That'll take a while, though, as I've
kind of run out of gold at this point because of having to spend so much on
the Armoire. I can also repost this in the correct section if that would be
helpful.

**Comment by lemoness** [comment]
Unfortunately, if that's the case, it's probably just due to bad luck, as I haven't seen any other reports. However, if you do track it and verify some odd statistics, please feel free to reopen a ticket in the main Habitica repo! Good luck.
