### ISSUE TITLE
Death When the IOS Can't Connect to the Server

### ISSUE THREAD

**Issue by Kgatliffe** [HabitRPG/habitrpg-ios#376]
I upgraded to the new version last night. Since then, if I make an action and the app can't connect to the server, I get the death screen, then the standard can't connect to server message, then I see my character with no health or mana, then it goes back to normal. I'm pretty sure that I am not losing levels or items.

It happened a number times this morning when I had a good connection and then an hour ago when I had no wifi. I was actually trying to trip it up a lot when I had weak connections that usually give me trouble ... but it was doing great today!

It doesn't seem to be doing real damage, just a surprise.

UUID: ddb68b6c-296a-4dd2-abaf-dd1f562ac140
Browser: iOS App
OS: iOS 9.3.2

**Comment by Alys** [comment]
I'm sorry about this! Those are fake deaths being caused by a display glitch in the app. It is just a display issue and shouldn't be actually hurting your character, although I know how annoying it is. :( We're working on a fix now. Definitely let us know if your character sustains any permanent damage!
