### ISSUE TITLE
Purchased 30 Gems, 4 Disappeared

### ISSUE THREAD

**Issue by veryemmappropriate** [HabitRPG/habitrpg-ios#387]
On 6/8 I purchased 30 gems (with gold) on the desktop website, then went to lunch and left the window open. When I returned from lunch, 4 gems were gone and I was down to 26 gems. I had not made any purchases, nor were there any people who could have tampered with my site. 

I checked to see if the gold I used to purchase the gems had been returned to my account, but I had used all of my gold to purchase the gems and some items from the armoire, and my gold was at 0. My gold was still at 0 after the gems disappeared.

Please help!

**Comment by vIiRuS** [comment]
Hi,

Is your gem count the same on both the app and the website? If you check the market on the website does it display that you can't buy any more gems this month?

**Comment by veryemmappropriate** [comment]
Hello!

1) Yes, I just checked and the gem count is the same on both desktop and
the app.
2) The gem counter says that I can still purchase 4 more gems. (But I know
with certainty the gold that I purchased the missing 4 gems with was not
returned to my account)

I hope that is helpful.

**Comment by vIiRuS** [comment]
After also checking your post in the report a bug guild, here is what probably happened:

1. you tried to purchase 30 gems rapidly. 26 got actually bought.
2. you spent the remaining money (including the money for those 4 gems that weren't bought) in the armoire.

So the gold wouldn't return, because you spent it in the armoire. So you can either wait until you have enough gold again to purchase those 4 gems or if you feel like you should have the gold anyway, you can also give yourself more gold by using the "Fix Character Values" in the website settings.

Also, this repository is for issues with the iOS app, which isn't the case here, so this isn't the right place to report an issue like this.

**Comment by veryemmappropriate** [comment]
I'm sorry that I posted in the wrong thread, but I didn't "try" to purchase
30 gems but only purchase 26. The gem count at the TOP of my screen was at
30 when I left for lunch, and then was at 26 when I returned. That
clearly sounds like a glitch to me. I'm sorry I didn't take a screencap of
the gems before I went to lunch but I didn't realize they would disappear.

If I need to direct this issue to someone else please let me know, but what
you are presuming happened is not the case.

**Comment by crookedneighbor** [comment]
@veryemmappropriate What probably happened is you experienced a sync error, where the website thought it had successfully purchased 30 gems, but it actually only purchased 26. This can happen sometimes with rapid fire clicking. The current gold the website _thought_ you had would then have been sent as an update on the next sync, and the gem count would have been returned to what was actually saved.

We're working on better resolution for site/server conflicts like this, but in the meantime, like @vIiRuS said, you can use the Fix Character Values to restore any gold that was unfairly taken.

**Comment by veryemmappropriate** [comment]
Thanks for the feedback.
