### ISSUE TITLE
Challenges: categories text is styled wrong

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#584]
the text for categories looks very technical right now ie: "habitica_official" instead of "Habitica Official"

**Comment by phillipthelen** [comment]
Main issue with this is that the data the API returns isn't correct for this. The challenge objects have a "slug" and "name" field, however both are the same string (in this case "habitica_official"). imho this should be looked at/fixed on the api, since it doesn't seem to work as intended right now

**Comment by schrockblock** [comment]
Looks like @SabreCat is taking care of this server-side. Closing here.
