### ISSUE TITLE
Tavern/Report a bug: add reason why button doesnt work

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#585]
Now that we're redoing tavern and making the report a bug function even more prominent, would we be able to add that pop-up we discussed that explains why the button doesnt work (ie you need an email address assigned in apple whatever

Also in tavern, when i tap report a bug, i expected to just be brought to a form that allowed me to do that, and when i instead saw the screen we currently show i was confused. is there a particular reason we want to show that intermediate screen first? Cause right now i have to press 'report a bug' 'report a bug' twice in two different areas.

**Comment by saraolson** [comment]
NEW COPY \o/

"Your email isn't set up yet

Whoops, looks like you haven't set up your email on this phone yet. Configure an account in the iOS mail app to use this quick-reporting option, or just email us directly at mobile@habitica.com"

**Comment by Alys** [comment]
Do you want to mention the Report a Bug guild as well? It's often the best place for bug reports since we can see their Habitica account and gain proof of ownership, both of which can be difficult from an email. It also gets faster responses for common bugs since the few Socialites that help there are familiar with the ongoing bugs that are reported often.

**Comment by saraolson** [comment]
@Alys id rather not at the moment but possibly in the future. mobile guilds are not in a good place right now, we dont have any way to notify you of new messages (unlike if they join on web, they at least have the notif panel) and there's no easy ctrl F on mobile to find your username.
