### ISSUE TITLE
Chat: Messages stop going through after you post 2 messages

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#624]
There's no indication of why, and it doesnt keep the text in the textbox. 

Eventually i kept spamming until i got the actual error message which we need to change the copy for because its a paragraph of tiny text thats only on screen for like 1-2 seconds, long enough for me to only read 'whoops'

**Comment by Alys** [comment]
It's this message:

 "messageGroupChatSpam": "Whoops, looks like you're posting too many messages! Please wait a minute and try again. The Tavern chat only holds 200 messages at a time, so Habitica encourages posting longer, more thoughtful messages and consolidating replies. Can't wait to hear what you have to say. :)"

If you give me or another admin or mod your test account's User ID, we can give it a couple of contributor tiers which will remove the limitation for you.

We can't shorten that message because it's the approved one for this situation.

It would be good though to have the message stay on screen for long enough for you to read it. Ideally it would be on a screen where you have to tap a button to dismiss it. 

Also it would be ideal if the message you entered wasn't lost (e.g., if it was added back to the input box after this error is detected, so it would need to be saved to a temporarily storage when you're posting it, or perhaps the API's returned data includes the message - I'm not sure but it's worth checking).

The same handling (a more visible error and the user's text not being lost) needs to be done for the error that the API returns when you've tried to post a swear word or a slur. I was going to log an issue about that, but can we use this issue for those cases as well since it's basically the same situation?
