### ISSUE TITLE
Cron doesn't always automatically reset dailies, need to manually pull to refresh

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#770]
"Once cron occurs, the only way to get dailies to reset is to manually refresh (drag them down to get the spinning wheel)" It's happened for awhile in the past, more than once

**Comment by kevincoleman** [comment]
While this behavior can be kind of handy for manually handling a cron, it does seem like the wrong way to put power in users’s hands. It’s a bit hidden, and makes users work for a normal cron even after they know where to go.

Alternatives?
- Just auto cron at the set time
- move option to trigger cron into a more tucked away place and label it more clearly
- make a button explicitly for this feature instead of a pull-down spinner to proc it
- other?

I think I like the first two in combo...

**Comment by phillipthelen** [comment]
That the user has to use pull to refresh to get the dailies to display correctly is a bug that happens in rare cases. Not something that is intentional or happens often. The correct flow is:

1. User receives modal to check off remaining tasks (if there are any. if not, it crons automatically)
2. user checks tasks off and taps button on the modal to start their day
3. App completes the tasks and then runs cron
4. App updates the dailies to reflect the new day.

The bug described here happens when something between 3. and 4. goes wrong and 4 doesn't happen automatically and instead the user has to refresh the tasks manually.

**Comment by kevincoleman** [comment]
Ah ok. That flow sounds about right—however, in my experience that “something” happens most if not all days.

Would it be helpful to extract and submit logs or something?

**Comment by kevincoleman** [comment]
Revisiting this—

Both of my party members have to pull to refresh the list every new day they use the app. I myself have to do it every day as well. Unless there’s something strange about my party in particular, this sounds like it’s much more common than “rare”.

Do we have statistics on how often people manually pull down the list of dailies to cron? That might be a good place to start. Validate, reproduce, investigate, fix?

**Comment by phillipthelen** [comment]
It‘s not really possible to log this, since cron did already run at the point where the user is refreshing manually. The part that hasn‘t happened yet is the dailies displaying this. So there is no real way to reliably log this, since it‘s hard/impossible to distinguish from a regular refreshing. If it were that easy, we would have already tried it.

When the dialog to check off your remaining dailies appears, do you check off many tasks there? Also, how long do you wait after the dialog until you refresh manually? Just to be sure that the issue is not just that the request for refreshing the tasks already started st the point where you refresh manually

**Comment by kevincoleman** [comment]
Ah, makes sense on logging.

Sometimes I check off things on the modal for yesterday’s dailies, and sometimes I don’t check off anything. It doesn’t appear to make a difference.

I haven’t timed it, but I usually wait a few seconds. I think there have been times when I go do something else in-app first, so that would mean quite some time has passed before the manual reload. I’ll try waiting a couple minutes tomorrow to verify this behavior.

A party member just confirmed the need to manually refresh every time after trying it again today, and I saw it again too.

**Comment by kevincoleman** [comment]
Confirmed it’s not just a delay. After dismissing the modal for yesterday’s items the dailies list seems to be showing yesterday’s state until a manual load is initiated.

**Comment by kevincoleman** [comment]
I’m curious if anyone else can reproduce these symptoms.

**Comment by xanenv** [comment]
@kevincoleman Yes, this specific issue happens to me daily, on iPhone XR. Everything you describe is spot-on with my experience with the app.

**Comment by xanenv** [comment]
Another issue that happens when it attempts to have you check off items that you may have missed last night, is it shows failed that weren’t from yesterday. For example I have weekday and different weekend dailies, and this morning it showed dailies from the week, and if I click on them it marks negative points. So I just have to ignore them and start my day. When I do this, it doesn’t take off any points or health.

**Comment by kevincoleman** [comment]
Interesting. I’ve noticed some anomalies in the modal’s behavior too. You should spec that out in detail and open a separate issue.
