### ISSUE TITLE
Getting double notifications for quest starts

### ISSUE THREAD

**Issue by GiacomoLaw** [HabitRPG/habitrpg-ios#779]
Double notifications for quests starting and party events.

**Comment by phillipthelen** [comment]
This sounds like your device ended up in the database twice by accident (and thus being treated as two devices by the server). Can you tell me your habitica userID or username? Then I can delete all push devices from the server and your device can properly register again the next time it is launched.

**Comment by GiacomoLaw** [comment]
Sure, my username is dipperdolphin and id is 1951d08e-56af-445e-8554-f70633b6eaa6. 

Thanks!

**Comment by ikassim9** [comment]
You should delete your id..

**Comment by Alys** [comment]
@ikassim9 Thanks for your concern! "User IDs" like that one are public
knowledge within Habitica and knowing them isn't a security risk, so they
don't need to be kept secret. They're mostly equivalent to the
human-readable Usernames, with the main difference being that Usernames can
change but User IDs are permanent. Because of that, it's often better for
User IDs to be specified, in case long-term troubleshooting is needed. :)

**Comment by ikassim9** [comment]
My bad. I mix up User ID with token api. I am also facing this issue. Here is my user ID: 6c4dfa5f-9dd5-4787-9d59-63777664112a

**Comment by Alys** [comment]
@ikassim9 No worries. :)

I've fixed that for you.

For reporting bugs, you might find it more convenient to use the Report a Bug guild (which you can reach from the Help menu on the website), or for app-specific bugs the Menu > About > Report a Bug button which sends debugging information to the mobile team.
