### ISSUE TITLE
The app is half-translated

### ISSUE THREAD

**Issue by IgorChernyshov** [HabitRPG/habitrpg-ios#781]
Looks like there are some issues with translation of the app. I use RU version. Half of all text is translated, but the other half like item description, stats, quests are not.
At first I thought - well, ok, I'll go check translations, but all translations are marked as translated.
Then I opened the web site and turned out that all the translations are made - item descriptions, quests and so on.
I've opened an xCode project, but turned out storyboard strings are translated as well...
I don't have much programming experience, but if anyone can give me hints how to fix that - I'm willing to help.

**Comment by IgorChernyshov** [comment]
![img_0266](https://user-images.githubusercontent.com/31541000/51671515-2b390700-1fda-11e9-8b7b-9d5a660ce013.PNG)
![img_0267](https://user-images.githubusercontent.com/31541000/51671516-2b390700-1fda-11e9-9bc1-461d06d5261f.PNG)

**Comment by phillipthelen** [comment]
If the items are not translated, can you try logging into the website and making sure that your language is set to russian in the settings? And then maybe clear the cache in the app, so that it redownloads the data. It should then be in the correct language. Normally this process is handled automatically, so not sure what went wrong here

**Comment by phillipthelen** [comment]
I have identified the issue and it will be fixed in 2.3

**Comment by IgorChernyshov** [comment]
Much appreciated Phillip!
I tried to find the root cause by myself, but this project looks so complicated for me :(


>Пятница, 22 марта 2019, 14:24 +03:00 от Phillip Thelen <notifications@github.com>:
>
>I have identified the issue and it will be fixed in 2.3
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Чернышов Игорь

**Comment by phillipthelen** [comment]
It was not a trivial fix, since it turned out that the app was not handling translations for content at all. So all items, gear, quests, etc. were always in english unless the user changed their language on the website.
I also added that the language can be changed from within the app to something else from the system language.
