### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by namitoyokota** [HabitRPG/habitrpg-ios#790]
Be able to switch between normal and dark mode

**Comment by phillipthelen** [comment]
This would be very cool, but would require _substantial_ work, since we would have to extend the current theming support a lot. We will have to redefine the colors for various purposes (p.e. if gray700 is used as a background, set the background to a `backgroundColorDimmed` or something, so that we can then in the Theme set the to a very light or very dark gray depending on what theme is used. and then also do that for all text colors). And then assign all that in every view and viewcontroller.

I probably won't have time to really work on this for quite a while. However if a contributor (or multiple people) is willing to chip away at this, I'd be happy to merge in that work. For that I would prefer it if 1. the person starting this work gets in touch, so that we can decide on good naming for the various color definitions and 2. splits up the work into multiple chunks (p.e. one PR that updates the tasks page to be compatible, and then another for the group pages), so that it is easier to review and also creates less merge conflicts.

**Comment by phillipthelen** [comment]
I just remembered that I actually had some work on this stashed away, that I did a bit ago. I just pushed  that, since it doesn't interfere with the other themes. In case anybody wants to continue work on this, setting the current theme to `NightTheme()` in the `SetupTheme()` method in the `HabiticaAppDelegate`.

It obviously still needs a bunch of work, but should be a good start for anybody interested in helping out with this!
![simulator screen shot - iphone xr - 2019-03-08 at 14 37 08](https://user-images.githubusercontent.com/298062/54031899-52c1e880-41b0-11e9-9f1d-bffcbee1d4d2.png)

**Comment by phillipthelen** [comment]
I have put some more work into this in between other tasks and it's now at the point where it still needs tweaking, but everything should be covered by the theming. If people want to try it out, it is available in the [iOS testflight beta](https://habitica.fandom.com/wiki/Mobile_Beta_Test_App_for_iOS:_Habitica). There are 3 different options. Royal Night (the one pictured above), The Dark Task (a more traditional dark mode and less purple) and True Black (this one is for iPhones with an OLED screen).

**Comment by phillipthelen** [comment]
Our plan is to release dark mode publicly when iOS 13 launches in september. That will then also include iOS specific features like automatically switching between light and dark mode. The themes will also all be available on devices that aren't running iOS 13, but will miss some of the features. I might also expand the themes, so that the tint color (purple, red, green, and so on) is separate from the app being light or dark. The next comment will be a list of things that are still buggy or that still need to be done.

**Comment by phillipthelen** [comment]
- [x] Handle iOS 13 theme switching
- [x] Creat dark variants of all tint colors
- [ ] True dark theme has chat message not readable if you are mentioned
