### ISSUE TITLE
Habit creation: Change default to ‘Positive’ active and ‘Negative’ inactive

### ISSUE THREAD

**Issue by kevincoleman** [HabitRPG/habitrpg-ios#800]
When creating a new habit both positive and negative are selected. In order for the user to appropriately select the one they want they have to tap the _other_ option to un-highlight it. 

![image](https://user-images.githubusercontent.com/445707/55903249-13593400-5b82-11e9-8311-e19dd86bad06.png)
![image](https://user-images.githubusercontent.com/445707/55903256-181de800-5b82-11e9-9eaa-f0c36a970a4a.png)
![image](https://user-images.githubusercontent.com/445707/55903264-1ce29c00-5b82-11e9-9a4d-f8c453c92808.png)
![image](https://user-images.githubusercontent.com/445707/55903269-1fdd8c80-5b82-11e9-8b66-85d5376fd2a9.png)

This is confusing UX. I noticed this because I saw myself and other users doing this:

- Tap the one they _want_, which un-selects it
- Realize they did it backward
- Tap the one they want again, to re-select it
- Tap the one they don’t want
- Continue

Since it doesn’t actually make a lot of sense to have the default state be having both selected (since habits aren’t both positive and negative), I suggest we solve the problem by taking two actions:
1. Make one or the other be selected by default (I lean toward positive being selected, because actively building good habits is one of the best ways to stop enforcing their counterpart bad habits)
2. Change the selection button(s) to something more like a toggle switch in between the plus and the minus. This would make it immediately apparent to the user that they’re in fact selecting one _or_ the other, not both or neither (which really shouldn’t be options for habits), and they wouldn’t do the above dance of confusion to figure out how the selection works.

**Comment by saraolson** [comment]
i'd be okay with changing the default to only positive selected. the original design for task creation on web had both selected as default, so this pattern is merely carry-over from that. 

however, the second point about a toggle between either positive and negative isn't viable. having both a positive and negative habit is a feature many users make use of for an action they can either act constructively or destructively towards. it's also used to stop the automatic degradation of task health, leaving it completely up to the user's inputted actions how healthy or unhealthy the task is. 

while both should be able to be selected, i'm not aware of a reason why none should be. that may be a bug. i'll ask the team for insight on that one.

**Comment by saraolson** [comment]
turns out being able to select none was something to give to users for if they wanted placeholders, spacers, headings, or a colorless place to add inspirational messages to themselves. so it is in fact intended and present on all platforms

**Comment by kevincoleman** [comment]
Sorry for the delay—I thought I was watching this...

About the default selection, I think my main gripe is not about what the default is so much as just that it creates an inverted reaction, where most of the time users have to deselect something when they’re expecting to have to select something. I think picking either positive or negative to be selected by default would solve this because users could see the two states of the buttons and would expect that by tapping either they’d be toggling the state. Though, to play devil’s advocate, showing one selected and the other not selected, users might assume the buttons should function like a radio buttons, at which point they’d be surprised when they toggle state independently of one another like check boxes.

I guess I can see why in some cases users might see the same habit as positive sometimes and negative other times... but it does seem more like an edge case than it does the “standard” usage. That said, I’m not angling to remove edge-case features that people love, so that ship has sailed.

As far as selecting none, it seems like...
- ...creating a placeholder item would be better accomplished with a draft feature
- ...inserting spacers would be better accomplished with a spacer feature or the ability to create sections that are naturally spaced a bit.
- ...inserting a headline would be better achieved by allowing a headline type of item. Using a habit as a headline is clearly a hack (it’s one I use, in fact). Making headlines a proper feature would both highlight the feature’s existence and clean up the habit creation process.
- ...inspirational messages? I get that people may like that, but the idea of a habit list is for listing actionable habits, not listing non-actionable motivational phrases. It seems like there could be a better place for listing non-actionable motivational phrases. It could actually be pretty cool to allow users to create custom affirmations that are tailored to the habits/tasks so they get affirmed when they tap complete.

Selecting none actually makes an otherwise actionable habit a no-op, which seems slightly off.

I realize replacing these things would take a bit more feature development, but I don’t think a lack of other features should properly defend a malformation of an existing feature. Honestly, some of the above hacks/features feel like they came out of crowd-sourced UX. Just because _someone_ wants it isn’t a good reason to build it. If we’re able to put some logical direction in place around what gets added and how it gets implemented, there may be opportunity to improve the product quality.

I realize some of this is disagreeable. I apologize. I’m not trying to start fights—just trying to lend fresh eyes to the user interaction side of the app.

**Comment by saraolson** [comment]
@kevincoleman We definitely understand your standpoint and even agree with most if not all of your reasoning, so this isn't so much a new perspective but a standpoint we've discussed at length and decided is not something we'd like to take out of power user's workflows at the moment. Like you said, that ship has sailed and its a lot more difficult to remove things people have gotten used to.

Habitica was crowd-sourced UX for a long time because it was an open source project without a design team behind it. I can guarantee you that the design team here now are experienced and aware of UX principles. While we have a strong stance recently and going forward where we focus new UX on the needs of the average user, there are some old features we've deemed less detrimental to the wider use case we're okay with keeping around. This happens to be one of them. They may seem extraneous to us, but they're truly helpful to certain subsets of users and we support that.

In the past, Habitica also made use of a lot of work-arounds that may seem less than ideal now, but it was a way to fill user's needs when resources were limited. We're still a very small team even now, even though we have a few full-time members that do more vetting than in the past. But this means we still rely on a lot of these work arounds because we don't have the resources to put into actually coding a new feature for something that isn't highly used. 

I hope this helps explain where we're coming from. I'm going to edit the title of this issue to reflect the changes to the default state of the +/- settings during Habit creation since our team is comfortable with making that change to help display the varying states upfront.

**Comment by kevincoleman** [comment]
@saraolson thanks for taking the time to parse all this, and respond so thoughtfully. This makes good sense to me.

I’m glad to hear Habitica folks are staffed with capable people (I hadn’t doubted). I do mainly web dev so I’m not a huge resource for Android/iOS, but I do enjoy critical thinking re: UI/UX. I’ll do my best to keep contributing meaningfully. I love Habitica and its community. \o/

Good action item on the +/- default state, I think. Thanks for hearing me out there. I definitely learned a lot by raising the other questions, so thanks for your time. :)

Best—

**Comment by Alys** [comment]
@kevincoleman If you're curious to see how players use Habits with both plus and minus configured, there's several examples at https://habitica.fandom.com/wiki/Sample_Habits . That page is aimed at new players so the examples are all pretty simple (e.g., "drink water / soda", "take stairs / elevator") but it gives an idea of how it can be useful.

**Comment by kevincoleman** [comment]
@Alys thanks! That helps it make sense. 🙏🏻
