### ISSUE TITLE
Open dailies badge count doesn't update automatically

### ISSUE THREAD

**Issue by rggjan** [HabitRPG/habitrpg-ios#841]
Due dailies can be displayed on the badge count. When finishing all dailies the badge number disappears.

However, I would expect the number to appear automatically again on the next day. This doesn't happen, you have to open habitica, go to dailies and reload to get the correct badge number.

**Comment by phillipthelen** [comment]
This doesn’t really work with how habitica handles days. Since you have to manually advance to the next day by completing remaining dailies. So before opening the app habitica technically is still on the old day.
This would also not work super reliably with iOS background excecution since we can’t ensure when that runs, because it’s determined by the OS itself.

**Comment by rggjan** [comment]
Could it be advanced automatically at least if there are no open dailies?
Also, how do messengers handle this? They can also update the badge count automatically whenever a new message arrives...

**Comment by fiuzaB** [comment]
> 
> 
> Could it be advanced automatically at least if there are no open dailies?
> Also, how do messengers handle this? They can also update the badge count automatically whenever a new message arrives...

Probably by push notification.
