### ISSUE TITLE
Tasks: Deleting a task sometimes doesn't update UI, can lead to unintended task deletion

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#879]
Sometimes when you try to delete a task, the task won't be removed from the list even after a pull to refresh. If you try to delete the task again, the same thing will happen, but on the back-end the app processes this as deleting the next task in line. This can lead to accidentally deleting many tasks before you know it.

Closing the app and reopening will show the task list without the deleted tasks.

**Comment by peterchu999** [comment]
hey @saraolson can i give it a try ?

**Comment by saraolson** [comment]
@peterchu999 you're welcome to take it on! we've tried to solve this before but it was difficult to reproduce reliably and thus difficult to troubleshoot. i'll mark this as in progress, good luck!

**Comment by peterchu999** [comment]
thanks @saraolson i'll try my best

**Comment by peterchu999** [comment]
hey @saraolson i'm sorry but i don't think i can fix this, maybe you can change the status.

**Comment by saraolson** [comment]
@peterchu999 that's okay, thank you for giving it a shot! it's always appreciated.

**Comment by phillipthelen** [comment]
I have some changes that might fix this but will need some more testing

**Comment by shanaqui** [comment]
A user has reported this again: "Delete or adding dailies. Page doesn’t update. I accidentally deleted all my dailies because I kept trying to delete the first one, since it stuck there."

iOS Version: 14.0.1
Device: iPhone XS Max
App Version: 3.0.3 (520)
User ID: a265a8ee-9760-482a-a6c6-c224975539f3
Level: 4
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

**Comment by saraolson** [comment]
@shanaqui can you please keep reporting to this issue when this happens for anyone else? would like to see how often it happens to judge priority at looking at it again since this one has always been tough to replicate and figure out.

**Comment by shanaqui** [comment]
"Tried to remove an outdated task, but despite multiple attempts it didn't disappear. Switching page back and forth I apparently removed ALL my dailies. 🤦‍♂️"

iOS Version: 14.2
Device: iPhone SE (2nd generation)
App Version: 3.1.3 (532)
User ID: 46f0dc73-dab2-41a1-b3a1-23ba2a5b7f9a
Level: 2
Class: warrior
Is in Inn: true
Uses Costume: false
Custom Day Start: 0

**Comment by shanaqui** [comment]
"Hi,

I tried to delete a daily.
Swiped left, “delete” appeared, I clicked it, but nothing seemed to happen. Daily was still there.
So I swiped again, clicked the button, no changes.
Did it again.
And again.
Again..

As it did not seem to work and nothing happened, I thought maybe quit the app and relaunch.

Then I found that 5 of my dailies were gone...

So it seems the delete did work, but it just did not show.

With each new try, even though it showed me clicking delete on the same daily that would not go away, I seemingly deleted the next, and the next etc.

Can I restore those dailies please?

Kind regards,

Coen."

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.2
Device: iPad Pro (12.9-inch) (2nd generation)
App Version: 3.1.1 (526)
User ID: 13e626d8-fcc8-4b2c-b560-605feb796ef2
Level: 9
Class: warrior
Is in Inn: true
Uses Costume: false
Custom Day Start: 0

**Comment by shanaqui** [comment]
"I tried to delete a task and it wouldn’t delete right away.  So I kept pulling delete and when I refreshed the menu, all of my tasks had been deleted!  Even though I only pulled delete on that one task (I swear, I’m not an idiot).

That’s a big bug in my option.
It shouldn’t be so slow to refresh that I lose all my tasks.  Also it’s the same problem for creating tasks.  I create a talk and then if I want to see it, I have to refresh the task list.

That kind of really sucks.
I was planning on using this app, but I’m having second thoughts because of the non-existent refresh time.

Maybe have the app sync at a later time online instead of having the app communicate with the server back and forth like that.  I’m assuming that’s why the hella weird bug where the task isn’t put on the list right away or deleted right away.
That must also be way deleting the same task multiple times deleted other tasks as well.
I’m guessing I pull delete and it tells the server to delete the task in that position on the list.
Because the task I deleted multiple times was on the top of the list.

Anyways just a suggestion and pointing out a bug that I could fix in my sleep.
No task list app should have problems with showing created tasks, as soon as they are created and removing deleted tasks, as soon as they are deleted.





The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.3
Device: iPhone XS Max
App Version: 3.1.3 (532)
User ID: 4a1d1025-b20e-486f-8aa8-8e41d8a82bd6
Level: 1
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 12"

**Comment by saraolson** [comment]
going to reassign this to 3.3 to take a look again :/ annoying that it came back..

**Comment by shanaqui** [comment]
A new one just in case it helps investigate!

> Hi
> 
> Sometime the UI is not refreshed after an action. As an example, I lost all my todo tasks because I tried to delete one of them. The ui made me think that the deletion of this specific task was not working. Actually, each time I did a swipe on this task to delete it, the other tasks were deleted as well... As the was not refreshed, it made me think that this did not work...
> Now i have to recreate all my to do tasks :)
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.4
> Device: iPhone XS
> App Version: 3.2 (567)
> User ID: 1da11b85-370f-40a7-a096-02810911584a
> Level: 3
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by shanaqui** [comment]
Never rains but it pours:

> Last night I was attempting to delete a daily item and each time I dragged left the trash can icon and red bar would I appear, but then it would “snap back”. I tried many times and couldn’t get it to work. I gave up and went to bed.
> 
> I woke up and almost all of my dailies were gone! I am assuming that even though the display was changing, each time I dragged left it was deleting a daily from my list.
> 
> 
> 
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.4
> Device: iPhone 11 Pro Max
> App Version: 3.2 (567)
> User ID: bc5bea8c-f7df-4888-8a69-ecea4d7a77c1
> Level: 18
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by shanaqui** [comment]
And another:

> I was trying to delete a daily task (the daily task was also a list). Delete button didn't work so I tried it a couple more times. Then I tried reloading the app and it had deleted the intended task as well as nearly all the other ones. *Cry*
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.4
> Device: iPhone 8
> App Version: 3.2 (567)
> User ID: 087b8a88-b85f-4069-b7d9-259665439ae2
> Level: 7
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 8

**Comment by saraolson** [comment]
we've had a few of these crop up again

> In the process of trying to delete one of my dailies it would allow me to swipe but would not allow me to press the delete button.   I kept trying to delete one of my dailies.   Then when I went to a different screen and came back several of my dailies were gone.   Is there anyway to recover my lost daily‘s.   They were deleted from this account at around 6 PM Eastern time today January 20
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.2.1
> Device: iPhone 12 mini
> App Version: 3.4.4 (649)
> User ID: 5146f432-406f-4e3f-9901-3e186cc58b2d
> Level: 21
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by saraolson** [comment]
> I was trying to delete something from my Habits tab, and it didn’t seem to work the first couple of times that I tried; when I swiped to delete it did nothing. So I restarted the app and when I opened it again most of the things from my Habits tab disappeared. It was probably a glitch and they got deleted when I was swiping to delete the other thing in the first place.
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.1.1
> Device: iPhone 12 mini
> App Version: 3.4.4 (649)
> User ID: ade7200f-5f79-4812-a45a-ae05a71d233a
> Level: 20
> Class: rogue
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
