### ISSUE TITLE
Chat: Message won't expand to show interaction options when there's a link

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#889]
when trying to reply to a post ending in a link, the interaction options (reply, report ect) won't show, only the link gets focus. 

In the case of a chat message having a link, tapping anywhere else around the message box should be able to expand the message. The link should be a smaller tap area

**Comment by juanj** [comment]
This seems to be the default behavior of links on a `UITextView`.
The tappable area seems to change depending on the context and is unpredictable. I been thinking on some solutions and this is what I got so far.

### Solution 1
Stop using the default behavior of `UITextView` to handle links and instead load the links as attributed string with the link styling and keep a list of links on the current view and their ranges. Then add a tap gesture recognizer that check if the characters under the tap location are part of a link and, if they are, handle the link.

The drawback with this solution is that we lose the selecting style that is applied to the link when you are tapping it, plus any other default behavior. Also, I'm not sure if adding a tap gesture recognizer will prevent the `UITextView` from selecting text.

### Solution 2
Keep the default behavior of  `UITextView` but create a subclass that overrides `func point(inside point: CGPoint, with event: UIEvent?)` as described on [this stackoverflow answer](https://stackoverflow.com/a/44878203) . 
This way the `UITextView` can only detect events directly on top of the links.

The drawback of this solution is that because the `UITextView` can only detect events on top of links, the rest of the text is not selectable.

### Solution 3
Use a web view to render messages.
I think the drawbacks with this solution will be to many.


---
And lastly one solution I been thinking on is to do some reverse engineering on how `UITextView` works and try to find a way to control the tappable area of the links. The problem with this is that this will most likely involve private API's (unless we find a method we can override like on solution 2) thus is out of the question.

@phillipthelen do you have any thoughts on this issue?

**Comment by phillipthelen** [comment]
Hey,

I think solution 2 sounds like the cleanest approach.

**Comment by saraolson** [comment]
@juanj should i mark this issue as in progress for you?

**Comment by juanj** [comment]
@saraolson Yes, I would like to work on this issue.
