### ISSUE TITLE
Create Widget for Habitica

### ISSUE THREAD

**Issue by ankit8697** [HabitRPG/habitrpg-ios#912]
I think it would be really cool if there was a widget for the app. Some ideas are the small one having your dailies, the medium one having dailies and todos, and the large one having dailies, todos, habits, and your HP and such. I haven’t tried making widgets yet but it sounds like it would be a nice feature to have.

**Comment by saraolson** [comment]
@ankit8697 this is definitely something we'd like to support but there seems to be a lot of limits with what iOS widgets can do. Like, you can't scroll content within a widget so a task list may be difficult to display. Also, in the largest widget you can have multiple tap targets, but it always opens the actual app to do the action so unsure how useful that is for checking off tasks.

We'll have to look into it more since iOS 14 just made widgets more mainstream and do further research on capabilities and best practices. If you have any specific widgets or behaviors you use that you'd like us to look at, we're open to suggestions!

**Comment by saraolson** [comment]
from a review: 
"It would be even more helpful if it had a widget for easy display of dailies and to-dos due that day."

**Comment by saraolson** [comment]
from a 2019 review lol: 
"I only wish it included a widget you could use to view and check off your lists more conveniently"

**Comment by saraolson** [comment]
We think our first priority for widgets will be:
-Dailies: current day overview
-Dailies: list of tasks
-Todos: list of tasks
-Create task buttons (create habit, create daily, create to do, create reward)

Other ideas:
-Individual tasks (ie drink water habit)
-Current quest progress
-Avatar
-HP/MP/EXP bars (combined with avatar in larger formats)

Wacky ideas:
-Randomly generated tasks, complete for special reward, button to add to your normal tasks if you like it
-Party chat?
-Pet you can tap to feed

open to more ideas

**Comment by phillipthelen** [comment]
I will untag the 3.2 milestone for this, because we have implemented all widgets that we will include with that update. More widgets will be added with future updates.

**Comment by oswinrodrigues** [comment]
> I will untag the 3.2 milestone for this, because we have implemented all widgets that we will include with that update. More widgets will be added with future updates.

@phillipthelen Does this mean that some widgets actually currently _do_ exist? If so, kindly point me to more information on this~ I tried looking around but found nothing. Thanks 🙏

**Comment by saraolson** [comment]
@oswinrodrigues we have a few widgets being tested in the 3.2 update that will be available when that releases, which should be very soon. its just the initial batch for now, we have a few more planned for later.

**Comment by oswinrodrigues** [comment]
I see it in the 3.2 release as of Feb 1, wohooo.
