### ISSUE TITLE
Ordered lists in Markdown (in guild description) not working

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#990]
A user has reported this issue for their guide description. A normal list results in correct numbering up to 9, but 10 and onwards show a single digit instead of 10, 11, 12, 13, etc. 

![image](https://user-images.githubusercontent.com/8144640/111904352-71654600-8a3e-11eb-862e-2f05b84e1b5b.png)

**Comment by rolisanchez** [comment]
This is a problem in the HabiticaStyler, specifically in `func style(listItemPrefix`.

It is only considering one digit numbers for the lists:

str.replaceCharacters(in: NSRange(location: 1, length: 1), with: " ")

It is replacing the second character with a space (For example "1." becomes "1 "). But because of this, it is eliminating the second digit in "10.", becoming "1 .".

I could tackle this :)

**Comment by saraolson** [comment]
@rolisanchez if you'd like to take this on, feel free! I'll mark it as in progress for ya

**Comment by rolisanchez** [comment]
Created PR #1101 :)
